version: '3.1'

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "82:82"
      - "81:81"
    stdin_open: true
    tty: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
      args:
        - APP_PORT
    environment:
      - APP_PORT
    command: ["npm", "run", "dev", "--", "--port", "$APP_PORT", "--host"]
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - wordpress
    

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
