name: Deploy Frontend to Preview

on:
  push:
    branches: [frontend/**/*]
  pull_request:
    types: [labeled]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Check for label and branch
        run: |
          if [[ "${{ github.event.label.name }}" == "preview" && ${{contains(github.event.pull_request.head.ref, 'frontend')}} ]]; then
            echo "Deploying frontend preview..."
            # Add your deployment steps here
          fi
      - name: Run pull_request.head.re
        run: echo "This is a PR for ${{ github.event.pull_request.head.ref  }}"
      - name: Run pull_request.base.re
        run: echo "This is a PR for ${{ github.event.pull_request.base.ref  }}"
      - name: Run ub.event_name
        run: echo "This is a PR for ${{ github.event_name  }}"
      - name: Run github.event.label.name
        run: echo "This is a PR for ${{ github.event.label.name   }}"
