name: Deploy Frontend to Preview

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  log:
    if: ${{contains(github.event.pull_request.labels.*.name, 'preview') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for label and branch
        run: |
          if [[ "${{ github.event.label.name }}" == "preview" && ${{contains(github.event.pull_request.head.ref, 'frontend')}} ]]; then
            echo "Deploying frontend preview..."
            # Add your deployment steps here
          fi
      - name: Run github.event.pull_request.head.ref
        run: echo "This is a PR for ${{ github.event.pull_request.head.ref  }}"
      - name: Run github.event.pull_request.base.ref
        run: echo "This is a PR for ${{ github.event.pull_request.base.ref  }}"
      - name: Run github.event_name
        run: echo "This is a PR for ${{ github.event_name  }}"
      - name: Run github.event.label.name
        run: echo "This is a PR for ${{ github.event.label.name   }}"
      - name: Find PR comment
        uses: peter-evans/find-comment@v3.0.0
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'preview of this pull request'

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            A preview of this pull request is ready!
            See it at https://preview.atletiekregels.nl/${{ github.event.number }}/
          edit-mode: replace

        # - name: Create or Update Comment
        # You may pin to the exact commit or the version.
        # uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        # uses: peter-evans/create-or-update-comment@v4.0.0
        # with:
        #   issue-number: ${{ github.event.pull_request.number }}
        #   body: |
        #     This is a multi-line test comment
        #     - With GitHub **Markdown** :sparkles:
        #     - Created by [create-or-update-comment][1]

        #     [1]: https://github.com/peter-evans/create-or-update-comment
        #   reactions: '+1'

  # notify:
  #   uses: peter-evans/create-or-update-comment@v4
  #   with:
  #     issue-number: 1
  #     body: |
  #       This is a multi-line test comment
  #       - With GitHub **Markdown** :sparkles:
  #       - Created by [create-or-update-comment][1]

  #       [1]: https://github.com/peter-evans/create-or-update-comment
  #     reactions: '+1'
